#pragma once

#define LOG_UART_ERROR(...) LOG_ENTITY_ERROR(ID_DEV(ENT_UART), __VA_ARGS__)
#define LOG_UART_WARNING(...) LOG_ENTITY_WARNING(ID_DEV(ENT_UART), __VA_ARGS__)
#define LOG_UART_INFO(...) LOG_ENTITY_INFO(ID_DEV(ENT_UART), __VA_ARGS__)
#define LOG_UART_DEBUG(...) LOG_ENTITY_DEBUG(ID_DEV(ENT_UART), __VA_ARGS__)