#pragma once

#define LOG_UART_TEST_ERROR(...) LOG_ENTITY_ERROR(ID_TEST(ENT_UART), __VA_ARGS__)
#define LOG_UART_TEST_WARNING(...) LOG_ENTITY_WARNING(ID_TEST(ENT_UART), __VA_ARGS__)
#define LOG_UART_TEST_INFO(...) LOG_ENTITY_INFO(ID_TEST(ENT_UART), __VA_ARGS__)
#define LOG_UART_TEST_DEBUG(...) LOG_ENTITY_DEBUG(ID_TEST(ENT_UART), __VA_ARGS__)

#define UART_TEST_NUM 4
extern test_desc_t UART_tests[UART_TEST_NUM];