// Generated by PeakRDL-cheader - A free and open-source header generator
// https://github.com/SystemRDL/PeakRDL-cheader

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// reg - gpio_ctrl::dir
#define GPIO_CTRL_R_DIR_F_PIN_DIR_BM 0xff // pin_dir field bitmask
#define GPIO_CTRL_R_DIR_F_PIN_DIR_BP 0 // pin_dir field bit position
#define GPIO_CTRL_R_DIR_F_PIN_DIR_BW 8 // pin_dir field width
#define GPIO_CTRL_R_DIR_F_PIN_DIR_RESET 0x0 // pin_dir field reset value
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t pin_dir :8;
        uint32_t :24;
    } f;
    uint32_t all;
} gpio_ctrl_R_dir_t;

// reg - gpio_ctrl::out
#define GPIO_CTRL_R_OUT_F_PIN_OUT_BM 0xff // pin_out field bitmask
#define GPIO_CTRL_R_OUT_F_PIN_OUT_BP 0 // pin_out field bit position
#define GPIO_CTRL_R_OUT_F_PIN_OUT_BW 8 // pin_out field width
#define GPIO_CTRL_R_OUT_F_PIN_OUT_RESET 0x0 // pin_out field reset value
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t pin_out :8;
        uint32_t :24;
    } f;
    uint32_t all;
} gpio_ctrl_R_out_t;

// reg - gpio_ctrl::in
#define GPIO_CTRL_R_IN_F_PIN_IN_BM 0xff // pin_in field bitmask
#define GPIO_CTRL_R_IN_F_PIN_IN_BP 0 // pin_in field bit position
#define GPIO_CTRL_R_IN_F_PIN_IN_BW 8 // pin_in field width
#define GPIO_CTRL_R_IN_F_ALARM_BM 0x100 // alarm field bitmask
#define GPIO_CTRL_R_IN_F_ALARM_BP 8 // alarm field bit position
#define GPIO_CTRL_R_IN_F_ALARM_BW 1 // alarm field width
#define GPIO_CTRL_R_IN_F_ALARM_RESET 0x0 // alarm field reset value
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t pin_in :8;
        uint32_t alarm :1;
        uint32_t :23;
    } f;
    uint32_t all;
} gpio_ctrl_R_in_t;

// reg - gpio_ctrl::set
#define GPIO_CTRL_R_SET_F_SET_BITS_BM 0xff // set_bits field bitmask
#define GPIO_CTRL_R_SET_F_SET_BITS_BP 0 // set_bits field bit position
#define GPIO_CTRL_R_SET_F_SET_BITS_BW 8 // set_bits field width
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t set_bits :8;
        uint32_t :24;
    } f;
    uint32_t all;
} gpio_ctrl_R_set_t;

// reg - gpio_ctrl::clr
#define GPIO_CTRL_R_CLR_F_CLR_BITS_BM 0xff // clr_bits field bitmask
#define GPIO_CTRL_R_CLR_F_CLR_BITS_BP 0 // clr_bits field bit position
#define GPIO_CTRL_R_CLR_F_CLR_BITS_BW 8 // clr_bits field width
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t clr_bits :8;
        uint32_t :24;
    } f;
    uint32_t all;
} gpio_ctrl_R_clr_t;

// reg - gpio_ctrl::int_en
#define GPIO_CTRL_INT_R_EN_F_EN_BM 0xffff // en field bitmask
#define GPIO_CTRL_INT_R_EN_F_EN_BP 0 // en field bit position
#define GPIO_CTRL_INT_R_EN_F_EN_BW 16 // en field width
#define GPIO_CTRL_INT_R_EN_F_EN_RESET 0x0 // en field reset value
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t en :16;
        uint32_t :16;
    } f;
    uint32_t all;
} gpio_ctrl_int_R_en_t;

// reg - gpio_ctrl::int_sts
#define GPIO_CTRL_INT_R_STS_F_STATUS_BM 0xffff // status field bitmask
#define GPIO_CTRL_INT_R_STS_F_STATUS_BP 0 // status field bit position
#define GPIO_CTRL_INT_R_STS_F_STATUS_BW 16 // status field width
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t status :16;
        uint32_t :16;
    } f;
    uint32_t all;
} gpio_ctrl_int_R_sts_t;

// reg - gpio_ctrl::int_type
#define GPIO_CTRL_INT_R_TYPE_F_TYP_BM 0xffff // typ field bitmask
#define GPIO_CTRL_INT_R_TYPE_F_TYP_BP 0 // typ field bit position
#define GPIO_CTRL_INT_R_TYPE_F_TYP_BW 16 // typ field width
#define GPIO_CTRL_INT_R_TYPE_F_TYP_RESET 0x0 // typ field reset value
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t typ :16;
        uint32_t :16;
    } f;
    uint32_t all;
} gpio_ctrl_int_R_type_t;

// reg - gpio_ctrl::int_pol
#define GPIO_CTRL_INT_R_POL_F_POL_BM 0xffff // pol field bitmask
#define GPIO_CTRL_INT_R_POL_F_POL_BP 0 // pol field bit position
#define GPIO_CTRL_INT_R_POL_F_POL_BW 16 // pol field width
#define GPIO_CTRL_INT_R_POL_F_POL_RESET 0x0 // pol field reset value
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t pol :16;
        uint32_t :16;
    } f;
    uint32_t all;
} gpio_ctrl_int_R_pol_t;

// reg - gpio_ctrl::wdt_cfg
#define GPIO_CTRL_WDT_R_CFG_F_PRESCALE_BM 0x3 // Tick speed divider. 0=1ms, 1=10ms, 2=100ms field bitmask
#define GPIO_CTRL_WDT_R_CFG_F_PRESCALE_BP 0 // Tick speed divider. 0=1ms, 1=10ms, 2=100ms field bit position
#define GPIO_CTRL_WDT_R_CFG_F_PRESCALE_BW 2 // Tick speed divider. 0=1ms, 1=10ms, 2=100ms field width
#define GPIO_CTRL_WDT_R_CFG_F_PRESCALE_RESET 0x0 // Tick speed divider. 0=1ms, 1=10ms, 2=100ms field reset value
#define GPIO_CTRL_WDT_R_CFG_F_EN_BM 0x100 // 1: Enable Watchdog, 0: Disable field bitmask
#define GPIO_CTRL_WDT_R_CFG_F_EN_BP 8 // 1: Enable Watchdog, 0: Disable field bit position
#define GPIO_CTRL_WDT_R_CFG_F_EN_BW 1 // 1: Enable Watchdog, 0: Disable field width
#define GPIO_CTRL_WDT_R_CFG_F_EN_RESET 0x0 // 1: Enable Watchdog, 0: Disable field reset value
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t prescale :2;
        uint32_t :6;
        uint32_t en :1;
        uint32_t :23;
    } f;
    uint32_t all;
} gpio_ctrl_wdt_R_cfg_t;

// reg - gpio_ctrl::wdt_val
#define GPIO_CTRL_WDT_R_VAL_F_TIMER_BM 0xff // timer field bitmask
#define GPIO_CTRL_WDT_R_VAL_F_TIMER_BP 0 // timer field bit position
#define GPIO_CTRL_WDT_R_VAL_F_TIMER_BW 8 // timer field width
#define GPIO_CTRL_WDT_R_VAL_F_TIMER_RESET 0xff // timer field reset value
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t timer :8;
        uint32_t :24;
    } f;
    uint32_t all;
} gpio_ctrl_wdt_R_val_t;

// reg - gpio_ctrl::wdt_reload
#define GPIO_CTRL_WDT_R_RELOAD_F_RELOAD_BM 0xff // reload field bitmask
#define GPIO_CTRL_WDT_R_RELOAD_F_RELOAD_BP 0 // reload field bit position
#define GPIO_CTRL_WDT_R_RELOAD_F_RELOAD_BW 8 // reload field width
#define GPIO_CTRL_WDT_R_RELOAD_F_RELOAD_RESET 0x64 // reload field reset value
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t reload :8;
        uint32_t :24;
    } f;
    uint32_t all;
} gpio_ctrl_wdt_R_reload_t;

// addrmap - gpio_ctrl
typedef struct __attribute__ ((__packed__)) {
    gpio_ctrl_R_dir_t dir;
    gpio_ctrl_R_out_t out;
    gpio_ctrl_R_in_t in;
    gpio_ctrl_R_set_t set;
    gpio_ctrl_R_clr_t clr;
    gpio_ctrl_int_R_en_t int_en;
    gpio_ctrl_int_R_sts_t int_sts;
    gpio_ctrl_int_R_type_t int_type;
    gpio_ctrl_int_R_pol_t int_pol;
    gpio_ctrl_wdt_R_cfg_t wdt_cfg;
    gpio_ctrl_wdt_R_val_t wdt_val;
    gpio_ctrl_wdt_R_reload_t wdt_reload;
} gpio_ctrl_t;


static_assert(sizeof(gpio_ctrl_t) == 0x30, "Packing error");

#ifdef __cplusplus
}
#endif
