#pragma once

#define LOG_TEST_ERROR(...) LOG_ENTITY_ERROR(ID_TEST(ENT_LOG), __VA_ARGS__)
#define LOG_TEST_WARNING(...) LOG_ENTITY_WARNING(ID_TEST(ENT_LOG), __VA_ARGS__)
#define LOG_TEST_INFO(...) LOG_ENTITY_INFO(ID_TEST(ENT_LOG), __VA_ARGS__)
#define LOG_TEST_DEBUG(...) LOG_ENTITY_DEBUG(ID_TEST(ENT_LOG), __VA_ARGS__)

#define LOG_TEST_NUM 1
extern test_desc_t LOG_tests[LOG_TEST_NUM];