#pragma once

#define LOG_GPIO_TEST_ERROR(...) LOG_ENTITY_ERROR(ID_TEST(ENT_GPIO), __VA_ARGS__)
#define LOG_GPIO_TEST_WARNING(...) LOG_ENTITY_WARNING(ID_TEST(ENT_GPIO), __VA_ARGS__)
#define LOG_GPIO_TEST_INFO(...) LOG_ENTITY_INFO(ID_TEST(ENT_GPIO), __VA_ARGS__)
#define LOG_GPIO_TEST_DEBUG(...) LOG_ENTITY_DEBUG(ID_TEST(ENT_GPIO), __VA_ARGS__)

#define GPIO_TEST_NUM 7
extern test_desc_t GPIO_tests[];